services:
  - type: web
    name: example-offramp-merchant
    env: static
    branch: main
    buildCommand: npm i && npm run build
    staticPublishPath: build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
